=== justinwritescode/Telegram/botmessage-schema2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "info": {
      "type": "object",
      "properties": {
        "message": {
          "type": "object",
          "properties": {
            "channel_data": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "object",
                  "properties": {
                    "from": {
                      "type": "object",
                      "properties": {
                        "username": {
                          "nullable": true,
                          "type": "string"
                        },
                        "first_name": {
                          "nullable": true,
                          "type": "string"
                        },
                        "last_name": {
                          "nullable": true,
                          "type": "string"
                        },
                        "is_bot": {
                          "nullable": true,
                          "type": "boolean"
                        },
                        "is_premium": {
                          "nullable": true,
                          "type": "boolean"
                        },
                        "language_code": {
                          "nullable": true,
                          "type": "string"
                        },
                        "id": {
                          "type": "integer"
                        }
                      }
                    },
                    "caption_entities": {
                      "nullable": true,
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "url": {
                            "type": "string"
                          },
                          "length": {
                            "type": "integer"
                          },
                          "type": {
                            "$ref": "/definitions/messageEntityType"
                          },
                          "offset": {
                            "type": "integer"
                          }
                        },
                        "required": [
                          "length",
                          "type",
                          "offset"
                        ]
                      }
                    },
                    "caption": {
                      "type": "string"
                    },
                    "video": {
                      "type": "object",
                      "properties": {
                        "thumb": {
                          "type": "object",
                          "properties": {
                            "width": {
                              "type": "integer"
                            },
                            "height": {
                              "type": "integer"
                            },
                            "file_id": {
                              "type": "string"
                            },
                            "file_unique_id": {
                              "type": "string"
                            },
                            "file_size": {
                              "type": "integer"
                            }
                          }
                        },
                        "file_name": {
                          "type": "string"
                        },
                        "height": {
                          "type": "integer"
                        },
                        "width": {
                          "type": "integer"
                        },
                        "file_unique_id": {
                          "type": "string"
                        },
                        "file_size": {
                          "type": "integer"
                        },
                        "duration": {
                          "type": "integer"
                        },
                        "mime_type": {
                          "type": "string"
                        },
                        "file_id": {
                          "type": "string"
                        }
                      }
                    },
                    "chat": {
                      "type": "object",
                      "properties": {
                        "username": {
                          "type": "string"
                        },
                        "first_name": {
                          "type": "string"
                        },
                        "last_name": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "id": {
                          "type": "integer"
                        }
                      }
                    },
                    "date": {
                      "type": "integer"
                    },
                    "message_id": {
                      "type": "integer"
                    }
                  }
                },
                "contact": {},
                "message_id": {
                  "type": "integer"
                },
                "chat_id": {
                  "type": "integer"
                }
              }
            },
            "id": {
              "type": "string"
            }
          }
        }
      }
    },
    "service": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "bot": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "external_id": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "contact": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "last_message": {},
        "photo": {},
        "variables": {},
        "telegram_id": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "date": {
      "type": "integer"
    }
  },
  "required": [
    "info",
    "service",
    "title",
    "bot",
    "contact",
    "date"
  ],
"defintions": {
  "messageEntityType": {
    "type": "object",
    "properties": {
      "offset": {
        "type": "integer"
      },
      "length": {
        "type": "integer"
      },
      "url": {
        "type": "string",
        "format": "uri"
      },
      "user": {
        "$ref": "/definitions/user"
      },
      "language": {
        "type": "string"
      }
    }
  },
  "user": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "is_bot": {
        "nullable": true,
        "type": "boolean"
      },
      "first_name": {
        "nullable": true,
        "type": "string"
      },
      "last_name": {
        "nullable": true,
        "type": "string"
      },
      "username": {
        "nullable": true,
        "type": "string"
      },
      "language_code": {
        "nullable": true,
        "type": "string"
      },
      "can_join_groups": {
        "nullable": true,
        "type": "boolean"
      },
      "can_read_all_group_messages": {
        "nullable": true,
        "type": "boolean"
      },
      "supports_inline_queries": {
        "nullable": true,
        "type": "boolean"
      }
    }
  },
  "entityType": {
    "type": "string",
    "enum": [
      "bold",
      "bot_command",
      "cashtag",
      "code",
      "custom_emoji",
      "email",
      "hashtag",
      "italic",
      "mention",
      "phone_number",
      "pre",
      "spoiler",
      "strikethrough",
      "text_link",
      "text_mention",
      "underline",
      "url"
    ]
  }
}
}

=== justinwritescode/Telegram/botmessage.json
[
  {
    "info": {
      "message": {
        "channel_data": {
          "message": {
            "date": 1674209092,
            "video": {
              "thumb": {
                "width": 320,
                "height": 320,
                "file_id": "AAMCAQADGQEAAkLtY8pnREPlJlqIBriYm-Z90ZPvQ5EAAkMCAAKAO1hGESElk6R7N6gBAAdtAAMtBA",
                "file_unique_id": "AQADQwIAAoA7WEZy",
                "file_size": 26200
              },
              "file_name": "IMG_9417.MOV",
              "height": 1920,
              "width": 1920,
              "file_unique_id": "AgADQwIAAoA7WEY",
              "file_size": 1509479,
              "duration": 3,
              "mime_type": "video/mp4",
              "file_id": "BAACAgEAAxkBAAJC7WPKZ0RD5SZaiAa4mJvmfdGT70ORAAJDAgACgDtYRhEhJZOkezeoLQQ"
            },
            "from": {
              "username": "justhorny32",
              "first_name": "Justin",
              "last_name": "Chase",
              "is_bot": false,
              "is_premium": true,
              "language_code": "en",
              "id": 1018982396
            },
            "message_id": 17133,
            "chat": {
              "username": "justhorny32",
              "first_name": "Justin",
              "last_name": "Chase",
              "type": "private",
              "id": 1018982396
            }
          },
          "contact": null,
          "message_id": 17133,
          "chat_id": 1018982396
        },
        "id": "63ca67444ea7120e423d1954"
      }
    },
    "service": "telegram",
    "title": "incoming_message",
    "bot": {
      "url": "https://t.me/BackroomSupport2Bot",
      "external_id": "5611963278",
      "id": "63023d314c7fa57fa00f7876",
      "name": "Backroom Support Bot¬≤"
    },
    "contact": {
      "username": "justhorny32",
      "name": "·íç·ëå·îë·é¢·èÜ·ëé ·ëï·ïº·ó©·îë·ó¥",
      "tags": [
        "üçë Size Queens: ASS! Participant"
      ],
      "last_message": null,
      "photo": null,
      "variables": {
        "my_issue": "Nope! You‚Äôre a fucking moron!",
        "name": "Justin",
        "media_caption": "https://www.google.com",
        "group_or_channel": "üí™üèª Muscles! Chanl",
        "may_we_identify_you_with_your_submitted_content": 1,
        "Whitelist Site URL": "https://www.foo.com",
        "username_for_check": "justhorny32",
        "contestant_telegram_username": "https://www.google.com",
        "contest_id": 2,
        "Whitelist Site Purpose": "Zoom Room Permalink",
        "media_url": "https://www.google.com",
        "Group or Channel": "The Backroom (grp) ‚ò£",
        "contestant_id": 49,
        "is_expecting_a_video_or_file": 0,
        "problem": "#SUGGESTION #REQUEST",
        "content_caption": "No caption",
        "last_name_for_check": "·ëï·ïº·ó©·îë·ó¥",
        "contestant_display_name": "https://www.google.com",
        "then_what": "request_unmute"
      },
      "telegram_id": "1018982396",
      "id": "63023d49d48a703beb59ca3b"
    },
    "date": 1674209092
  }
]
